"""Initial migration

Revision ID: 4d5711838421
Revises: d58e151452ac
Create Date: 2025-05-25 01:39:27.142519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5711838421'
down_revision: Union[str, None] = 'd58e151452ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
