"""atualizar

Revision ID: 7727f89263e4
Revises: 4d5711838421
Create Date: 2025-05-25 22:03:02.424044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7727f89263e4'
down_revision: Union[str, None] = '4d5711838421'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_products')
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('clients', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('orders', sa.Column('order_date', sa.DateTime(), nullable=False))
    op.add_column('orders', sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=True))
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.drop_column('orders', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_column('orders', 'total')
    op.drop_column('orders', 'order_date')
    op.alter_column('clients', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('clients', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('order_products',
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='order_products_order_id_fkey'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='order_products_product_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name='order_products_pkey')
    )
    # ### end Alembic commands ###
