"""atualizar

Revision ID: 846f6c134af3
Revises: c2ff73fea526
Create Date: 2025-05-26 00:05:16.979994

"""
# from typing import Sequence, Union # <-- Você pode remover esta linha também se não usar em outro lugar no arquivo

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846f6c134af3' # <--- REMOVA ': str'
down_revision = 'c2ff73fea526' # <--- REMOVA ': Union[str, None]'
branch_labels = None # <--- REMOVA ': Union[str, Sequence[str], None]'
depends_on = None # <--- REMOVA ': Union[str, Sequence[str], None]'


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.execute("UPDATE users SET username = email WHERE username IS NULL")
    op.alter_column(
        'users',
        'username',
        existing_type=sa.String(),
        type_=sa.String(),
        nullable=False,
        existing_nullable=True,
        postgresql_using='username::varchar'
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###